# Generated by Django 4.2.2 on 2023-06-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_profile_picture_remove_user_surname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
