# Generated by Django 4.2.2 on 2023-06-21 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('author', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('published_date', models.CharField(blank=True, default='', max_length=100)),
                ('publisher', models.CharField(blank=True, default='', max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('genre', models.CharField(default='Fiction', max_length=50)),
                ('ranking', models.IntegerField(default=0)),
                ('highlighted', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('category', models.CharField(blank=True, default='New', max_length=100)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='account.user')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
