# Generated by Django 4.2.2 on 2023-06-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_bookfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookfile',
            old_name='cloudinary_link',
            new_name='link',
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
